POST http://127.0.0.1:5000/user/login/
Content-Type: application/json

{
    "name":"zhangsan",
    "password":"123456"
}

### 测试用户注册功能
POST http://127.0.0.1:5000/user/users/
Content-Type: application/json

{
    "name":"zhangsan",
    "pwd":"123456",
    "rel_password":"123456",
    "phone":"18811100166",
    "email":"123456@nihao.com"
}

### 测试登陆验证器
GET http://127.0.0.1:5000/user/test/
# token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyfQ.SObxIkLXL2N00lapaMjLZRpFC5jpcVR6n_17frpHz0A